### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by nlf** [tjpeden/express-resource-new#2]
There's a bug when using nested resources in the same server module as unnested resources that you've already fixed in git, but it has not been published to npm. For convenience's sake it would be awesome if you could do that.

**Comment by tjpeden** [comment]
Yes, absolutely. I must have forgotten about that fix. It snuck in with some other change I made. I will definitely get that out for you today.

Thanks for your feedback, Nathan. Please continue to create issues as problems come up.

-TJ
